-- 코드를 입력하세요
SELECT o.PRODUCT_ID, p.PRODUCT_NAME, 
    SUM(p.PRICE * o.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER o
INNER JOIN FOOD_PRODUCT p
    USING (PRODUCT_ID)
WHERE o.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY o.PRODUCT_ID
ORDER BY SUM(p.PRICE * o.AMOUNT) DESC,  o.PRODUCT_ID ASC;