-- 코드를 입력하세요
WITH ANIMAL_INS_INTAKE AS (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE NOT LIKE 'Spayed%' AND
        SEX_UPON_INTAKE NOT LIKE 'Neutered%'
),

ANIMAL_OUTS_INTAKE AS (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR
        SEX_UPON_OUTCOME LIKE 'Neutered%'
)

SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS_INTAKE i
INNER JOIN ANIMAL_OUTS_INTAKE o
    ON i.ANIMAL_ID = o.ANIMAL_ID;