-- 코드를 입력하세요
WITH BEST_REVIEWER AS (
SELECT MEMBER_ID,
    COUNT(MEMBER_ID) AS COUNT_REVIEW
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(MEMBER_ID) DESC
LIMIT 1),
MEMBER_PRO AS (
    SELECT p.MEMBER_ID, p.MEMBER_NAME
    FROM BEST_REVIEWER b
    JOIN MEMBER_PROFILE p
    ON b.MEMBER_ID = p.MEMBER_ID
)

SELECT p.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PRO p
JOIN REST_REVIEW r
ON p.MEMBER_ID = r.MEMBER_ID
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC;