-- 코드를 입력하세요
SELECT DISTINCT(c.CAR_ID)
FROM (
    SELECT CAR_ID, CAR_TYPE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단'
) c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON h.CAR_ID = c.CAR_ID 
WHERE MONTH(START_DATE) = 10
ORDER BY CAR_ID DESC;