-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, PRODUCT_NAME
    FROM FOOD_PRODUCT
    WHERE (CATEGORY = '과자' or CATEGORY = '국' OR
    CATEGORY = '김치' OR CATEGORY = '식용유')
) AS SUABA
WHERE PRICE IN (
    SELECT MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY) 
ORDER BY PRICE DESC;