-- 코드를 입력하세요
WITH ON_SALES AS (
    SELECT USER_ID, SALES_AMOUNT, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
    WHERE SALES_AMOUNT > 0
)

SELECT o.YEAR, o.MONTH, u.GENDER, COUNT(DISTINCT(u.USER_ID)) AS USERS
FROM ON_SALES o
INNER JOIN (
    SELECT USER_ID, YEAR(JOINED) AS YEAR, MONTH(JOINED) AS MONTH, GENDER
    FROM USER_INFO 
    WHERE GENDER IS NOT NULL
) u
    USING (USER_ID)
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;