-- 코드를 입력하세요
WITH POSSIBLE_CARS AS (
    SELECT c.CAR_ID, c.CAR_TYPE, c.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR c
    WHERE c.CAR_TYPE IN ('세단', 'SUV')
      AND c.CAR_ID NOT IN (
          SELECT h.CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
          WHERE h.START_DATE <= '2022-11-30' AND h.END_DATE >= '2022-11-01'
      )
),
DISCOUNTED_CARS AS (
    SELECT p.CAR_ID, p.CAR_TYPE, p.DAILY_FEE, COALESCE(d.DISCOUNT_RATE, 0) AS DISCOUNT_RATE
    FROM POSSIBLE_CARS p
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
      ON p.CAR_TYPE = d.CAR_TYPE AND d.DURATION_TYPE = '30일 이상'
),
FEE_TABLE AS (
    SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * (1 - DISCOUNT_RATE / 100) * 30) AS FEE
    FROM DISCOUNTED_CARS
)

SELECT *
FROM FEE_TABLE
WHERE FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;