-- 코드를 작성해주세요
WITH TOTAL_SCORE AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT t.SCORE, t.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM TOTAL_SCORE t
LEFT JOIN HR_EMPLOYEES e
    USING (EMP_NO)
ORDER BY t.SCORE DESC
LIMIT 1;