-- 코드를 작성해주세요
WITH YEAR_DF AS (
    SELECT ID, SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
),
MAX_DF AS (
    SELECT MAX(SIZE_OF_COLONY) AS YEAR_MAX, 
        YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR
)


SELECT y.YEAR, (m.YEAR_MAX - y.SIZE_OF_COLONY) AS YEAR_DEV, y.ID
FROM YEAR_DF y
LEFT JOIN MAX_DF m
    ON y.YEAR = m.year
ORDER BY YEAR, YEAR_DEV;