-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, SUM(o.SALES_AMOUNT) * p.PRICE AS SALES
FROM PRODUCT p
RIGHT JOIN OFFLINE_SALE o
    USING (PRODUCT_ID)
GROUP BY p.PRODUCT_CODE
ORDER BY SUM(o.SALES_AMOUNT) * p.PRICE DESC, p.PRODUCT_CODE ASC;