-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, 
    CONCAT(u.CITY,' ', u.STREET_ADDRESS1,' ', u.STREET_ADDRESS2) AS '전체주소', 
    CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8, 4)) AS '전화번호'
FROM (
    SELECT WRITER_ID, COUNT(WRITER_ID) AS COUNT_GOODS
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID) >= 3
) b
JOIN USED_GOODS_USER u
ON b.WRITER_ID = u.USER_ID
ORDER BY u.USER_ID DESC;