-- 코드를 작성해주세요
WITH QUARTER_DATA AS (
    SELECT *,
        CASE
            WHEN MONTH(DIFFERENTIATION_DATE) <= 3 THEN '1Q'
            WHEN MONTH(DIFFERENTIATION_DATE) <= 6 THEN '2Q'
            WHEN MONTH(DIFFERENTIATION_DATE) <= 9 THEN '3Q'
            WHEN MONTH(DIFFERENTIATION_DATE) <= 12 THEN '4Q'
            END AS QUARTER
    FROM ECOLI_DATA
)

SELECT QUARTER, COUNT(ID) AS ECOLI_COUNT
FROM QUARTER_DATA
GROUP BY QUARTER
ORDER BY QUARTER ASC;