WITH REST_SCORE_INFO AS (
    SELECT r.REVIEW_ID, r.REVIEW_SCORE, i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS
    FROM REST_REVIEW r
    LEFT JOIN REST_INFO i
        ON r.REST_ID = i.REST_ID
)

SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_SCORE_INFO
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY AVG(REVIEW_SCORE) DESC, FAVORITES DESC;

