-- 코드를 입력하세요
WITH JOINED_21 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
SALES_21_USERS AS(
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM JOINED_21)
),
DISTINCT_BUYERS AS (
    SELECT YEAR, MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
    FROM SALES_21_USERS
    GROUP BY YEAR, MONTH
)

SELECT 
    d.YEAR,
    d.MONTH,
    d.PURCHASED_USERS,
    ROUND(d.PURCHASED_USERS / (SELECT COUNT(*) FROM JOINED_21), 1) AS PUCHASED_RATIO
FROM DISTINCT_BUYERS d
ORDER BY d.YEAR, d.MONTH;