-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', s.BOARD_ID, '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) AS FILE_PATH
FROM (
    SELECT BOARD_ID
    FROM USED_GOODs_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
) AS s
JOIN USED_GOODS_FILE f
ON s.BOARD_ID = f.BOARD_ID
ORDER BY f.FILE_ID DESC;