-- 코드를 입력하세요
WITH NOT_CANCEL AS (
    SELECT *
    FROM APPOINTMENT
    WHERE DATE(APNT_YMD) = '2022-04-13' AND APNT_CNCL_YN = 'N' AND
        MCDP_CD = 'CS'
)

SELECT c.APNT_NO, p.PT_NAME, p.PT_NO, d.MCDP_CD, d.DR_NAME, c.APNT_YMD
FROM NOT_CANCEL c
INNER JOIN PATIENT p
    ON c.PT_NO = p.PT_NO
INNER JOIN DOCTOR d
    ON c.MDDR_ID = d.DR_ID
ORDER BY c.APNT_YMD ASC;