-- 코드를 입력하세요
WITH SALES AS (
    SELECT USER_ID, PRODUCT_ID, COUNT(*) AS COUNTS
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    ORDER BY USER_ID
)

SELECT USER_ID, PRODUCT_ID
FROM SALES
WHERE COUNTS > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;