WITH DURATION AS (
    SELECT 
        HISTORY_ID, 
        CAR_ID, 
        DATEDIFF(END_DATE, START_DATE) + 1 AS RENT_DAY,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
        END AS RENTAL_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
),
CAR_RENTAL AS (
    SELECT 
        d.HISTORY_ID, 
        d.CAR_ID, 
        d.RENTAL_DURATION, 
        d.RENT_DAY, 
        c.CAR_TYPE, 
        c.DAILY_FEE
    FROM DURATION d
    JOIN CAR_RENTAL_COMPANY_CAR c
        ON d.CAR_ID = c.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
),
FINAL AS (
    SELECT 
        c.HISTORY_ID, 
        c.CAR_ID, 
        c.RENTAL_DURATION,
        c.RENT_DAY,
        c.CAR_TYPE, 
        c.DAILY_FEE, 
        IFNULL(p.DISCOUNT_RATE, 0) AS DISCOUNT_RATE
    FROM CAR_RENTAL c
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
        ON c.CAR_TYPE = p.CAR_TYPE 
        AND c.RENTAL_DURATION = p.DURATION_TYPE
)
SELECT 
    HISTORY_ID, 
    ROUND(RENT_DAY * DAILY_FEE * (1 - (DISCOUNT_RATE / 100.0)), 0) AS FEE
FROM FINAL
ORDER BY FEE DESC, HISTORY_ID DESC;