-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(s.TOTAL_SALES) AS TOTAL_SALES
FROM (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
) s
INNER JOIN BOOK b
    USING(BOOK_ID)
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;