-- 코드를 작성해주세요
WITH FISH_INFOR AS (
    SELECT ID, FISH_TYPE, LENGTH,
        RANK () OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS FISH_RANK
    FROM FISH_INFO
)

SELECT i.ID, n.FISH_NAME, i.LENGTH
FROM FISH_INFOR i
JOIN FISH_NAME_INFO n
    ON i.FISH_TYPE = n.FISH_TYPE
WHERE FISH_RANK = 1
ORDER BY i.ID ASC;