-- 코드를 입력하세요
WITH ANIMAL_DIFF AS (
    SELECT i.ANIMAL_ID, i.NAME, DATEDIFF(o.DATETIME, i.DATETIME) AS DATE_DIFF
    FROM ANIMAL_INS i
    INNER JOIN ANIMAL_OUTS o
        ON i.ANIMAL_ID = o.ANIMAL_ID
    ORDER BY DATEDIFF(o.DATETIME, i.DATETIME) DESC)

SELECT ANIMAL_ID, NAME
FROM ANIMAL_DIFF
LIMIT 2;