-- 코드를 작성해주세요
WITH FISH_LENGTH AS (
    SELECT ID, FISH_TYPE, COALESCE(LENGTH, 10) AS LENGTH
    FROM FISH_INFO
)

SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_LENGTH
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE ASC;