-- 코드를 입력하세요
WITH ICECREAM AS (
    SELECT *
    FROM FIRST_HALF
    UNION
    SELECT *
    FROM JULY
),
TOTAL_SALES AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_SALES
    FROM ICECREAM
    GROUP BY FLAVOR
    ORDER BY SUM(TOTAL_ORDER) DESC
)

SELECT FLAVOR
FROM TOTAL_SALES
LIMIT 3;